version: '3'

services:
  discovery-service:
    build:
      context: ./discovery-service
    image: discovery-service
    container_name: eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 60s
      timeout: 45s
      retries: 5
      start_period: 120s
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: cliente_persona
      MYSQL_USER: admin
      MYSQL_PASSWORD: Adm1ns
      MYSQL_ROOT_PASSWORD: Adm1ns
    ports:
      - "3306:3306"
    volumes:
      - ./resources/BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  cliente-persona-api:
    build:
      context: ./cliente-persona
    image: cliente-persona-api
    container_name: cliente-persona-service
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql:
        condition: service_started
  cuenta-movimientos-api:
    build:
      context: ./cuenta-movimientos
    image: cuenta-movimientos-api
    container_name: cuenta-movimientos-service
    ports:
      - "8081:8080"
    links:
      - mysql
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql:
        condition: service_started
